PackageIdentifier: RKNN3.Center
PackageVersion: 0.2.6
PackageLocale: en-US
Publisher: RKNN3 Center
PackageName: RKNN3 Center
ShortDescription: RKNN3 Center desktop application and device manager
ManifestType: defaultLocale
ManifestVersion: 1.6.0
